#!/usr/bin/env ruby
require 'juandpineiro_palindrome'

palindromes = File.readlines('phrases.txt').select(&:palindrome?)
palindromes.each { |palindrome| puts "palindrome detected: #{palindrome}" } 
File.write('palindrome_file.txt', palindromes.join)
