#!/usr/bin/env ruby
require 'open-uri'
require 'nokogiri'

# Returns the paragraphs from a Wikipedia link, stripped of reference numbers.
# Especially useful for text-to-speech (both native and foreign).

if ARGV.empty? || ARGV.length > 1
  puts 'Usage: wikp <URL>'
  exit
end

doc = Nokogiri::HTML(open(ARGV.shift).read)
doc.css('.reference').each(&:remove)
puts doc.css('p').map(&:content).join("\n")
